#!/bin/bash

set -e

SOURCE=src
TARGET=target
LIFT_LIB=".lift/algs4.jar"

chapterId=$1
sectionId=$2
exerciseId=$3
shift
shift
shift

exercise="Exercise${chapterId}_${sectionId}_$exerciseId"
folder="chapter$chapterId/section$sectionId"

javac-algs4 -sourcepath $SOURCE "$SOURCE/$folder/${exercise}.java" -d $TARGET

java="java"
if [ -f /usr/libexec/java_home ]; then
  # Use different command on OS X
  java="/usr/libexec/java_home -exec java"
fi

echo "Exercise ${chapterId}.${sectionId}.$exerciseId"
$java -cp "$TARGET:$LIFT_LIB" "$folder/${exercise}" "$@"
