#!/bin/bash

set -e

chapter=$1
section=$2
exercise=$3
shift
shift
shift

exercise_file="Exercise${chapter}_${section}_$exercise"
folder="chapter$chapter/section$section"

echo "Exercise ${chapter}.${section}.$exercise"
cd src
javac-algs4 "$folder/${exercise_file}.java" && java-algs4 "$folder/${exercise_file}" "$@"
cd ../
